{{- if .Values.nginxcertificates }}
apiVersion: v1
kind: Secret
metadata:
  name: bitwardenrs-local-tls
  namespace: default
data:
  {{- range $key, $val := .Values.nginxcertificates }}
  {{ $key }}: {{ $val }}
  {{- end }}
type: kubernetes.io/tls
{{- end }}
